### ISSUE TITLE
Re-flashing requires erasing existing partitions manually

### ISSUE THREAD

**Issue by kazazes** [balena-os/balena-intel#202] opened 2019-04-18 22:58 UTC
This behavior is new. I have had to erase partition tables in between flashes or it stalls. Reproduced on two different model NUCs. intel-nuc-2.31.2+rev1-dev-v9.11.1

**Comment by floion** [comment] 2019-04-19 09:35
What error do you get? Does it complain about overlapping partitions?

**Comment by kazazes** [comment] 2019-04-19 09:50
Yes. In the flash sequence and in GParted afterwards.

**Comment by floion** [comment] 2019-04-29 05:57
@agherzan @ZubairLK seems like some trouble with the labeling ^

**Comment by agherzan** [comment] 2019-04-29 13:57
@spanceac had a similar issue that he fixed and might be able to give us more details. Otherwise, @kazazes do you have an easy way to reproduce?

**Comment by floion** [comment] 2019-04-29 19:02
@agherzan the way @spanceac fixed it a while back was to wipe the partition table from u-boot shell (it happened on an armv7 board running uboot and the u-boot shell was available). Also, @acostach fixed another instance of this bug happening with this PR: https://github.com/balena-os/meta-balena/pull/1379

So it looks like there are other cases when this can happen

**Comment by floion** [comment] 2019-05-01 07:23
Related to this: https://github.com/balena-os/meta-balena/pull/1487

**Comment by floion** [comment] 2019-05-16 03:12
Should be fixed by https://github.com/balena-os/meta-balena/pull/1506 and https://github.com/balena-os/balena-intel/pull/210

**Closed** 2019-05-21 05:53 UTC

**Comment by kazazes** [comment] 2019-08-24 05:00
I can confirm that this is still in fact still present. Trying to flash a `2.38.3+rev4` dev image to a production `2.39.0+rev3` hangs at `Booting flash` with no more information. Wiping manually with another live image fixes the problem.

**Comment by agherzan** [comment] 2019-09-09 15:19
@kazazes are you able to reproduce this consistently? Can you give us some instructions to replicate it on our side? CC @floion
